version: "3.8"

services:
  web:
    image: kawaweb:latest
    container_name: ${CONTAINER_NAME}
    network_mode: bridge
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 6780:80
      - 6781:443
    #depends_on:
    #  - mysql
    #  - redis
    tty: true
    init: true
    volumes:
      - .:/srv/root
      - ${GULAG_PATH}/kawata.py:/srv/root/gulag
      - ${GULAG_PATH}/.data/b.py:/srv/root/.data/b.py
    environment:
      - TZ=${TZ}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - GULAG_ADDRESS=${GULAG_ADDRESS}
      - GULAG_PORT=${GULAG_PORT}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - APP_NAME=${APP_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - HCAPTCHA_SITEKEY=${HCAPTCHA_SITEKEY}
      - HCAPTCHA_SECRET=${HCAPTCHA_SECRET}
      - DOMAIN=${DOMAIN}
      - MAX_IMAGE_SIZE=${MAX_IMAGE_SIZE}
      - MAX_IMAGE_SIZE_SUPPORTER=${MAX_IMAGE_SIZE_SUPPORTER}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PATH_TO_GULAG=${PATH_TO_GULAG}
      - SEPERATE_DATA_PATH=${SEPERATE_DATA_PATH}
      - DEBUG_LEVEL=${DEBUG_LEVEL}
      - DISALLOWED_NAMES=${DISALLOWED_NAMES}
      - DISALLOWED_PASSWORDS=${DISALLOWED_PASSWORDS}
      - ENABLE_REGISTRATION=${ENABLE_REGISTRATION}
      - DISCORD_LINK=${DISCORD_LINK}